"""initial schema

Revision ID: b601e4eacebc
Revises: 
Create Date: 2026-07-07 10:03:58.723425
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b601e4eacebc'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


ENUM_TYPES = (
    "user_role",
    "application_status",
    "artifact_kind",
    "artifact_status",
    "verification_stage",
    "stage_status",
    "risk_band",
    "recommendation",
    "consent_status",
    "decision_type",
    "report_format",
    "notification_channel",
    "audit_action",
)


def upgrade() -> None:
    # Required extensions: citext (case-insensitive email) and pgcrypto
    # (gen_random_uuid on PostgreSQL < 13; harmless and explicit on 13+).
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'officer', 'applicant', 'auditor', name='user_role'), server_default='applicant', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('officers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(), nullable=False),
    sa.Column('branch_code', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_officers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_officers')),
    sa.UniqueConstraint('employee_code', name=op.f('uq_officers_employee_code')),
    sa.UniqueConstraint('user_id', name=op.f('uq_officers_user_id'))
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_refresh_tokens')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('risk_engine_config',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_risk_engine_config_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_engine_config')),
    sa.UniqueConstraint('version', name=op.f('uq_risk_engine_config_version'))
    )
    op.create_index('uq_risk_engine_config_active', 'risk_engine_config', ['is_active'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('applications',
    sa.Column('reference_no', sa.String(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('assigned_officer_id', sa.UUID(), nullable=True),
    sa.Column('loan_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('loan_purpose', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'processing', 'pending_review', 'needs_attention', 'more_info_requested', 'approved', 'rejected', name='application_status'), server_default='draft', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('loan_amount > 0', name=op.f('ck_applications_loan_amount_positive')),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], name=op.f('fk_applications_applicant_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['officers.id'], name=op.f('fk_applications_assigned_officer_id_officers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('reference_no', name=op.f('uq_applications_reference_no'))
    )
    op.create_index(op.f('ix_applications_applicant_id'), 'applications', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_applications_assigned_officer_id'), 'applications', ['assigned_officer_id'], unique=False)
    op.create_index('ix_applications_review_queue', 'applications', ['submitted_at'], unique=False, postgresql_where=sa.text("status = 'pending_review'"))
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('action', sa.Enum('user_login', 'user_logout', 'user_login_failed', 'application_created', 'artifact_uploaded', 'artifact_viewed', 'artifact_purged', 'pipeline_stage_completed', 'pipeline_stage_failed', 'risk_scored', 'officer_decision', 'report_generated', 'report_exported', 'retention_purge', 'role_changed', name='audit_action'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('prev_hash', sa.String(), nullable=True),
    sa.Column('entry_hash', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_audit_logs_application_id_applications'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_actor', 'audit_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_application', 'audit_logs', ['application_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_created', 'audit_logs', ['created_at'], unique=False)
    op.create_table('co_applicants',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('linked_user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('email', postgresql.CITEXT(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_co_applicants_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], name=op.f('fk_co_applicants_linked_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_co_applicants'))
    )
    op.create_index(op.f('ix_co_applicants_application_id'), 'co_applicants', ['application_id'], unique=True)
    op.create_table('notifications',
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('in_app', 'email', name='notification_channel'), server_default='in_app', nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_notifications_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notifications_recipient_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_recipient_unread', 'notifications', ['recipient_id', 'created_at'], unique=False, postgresql_where=sa.text('is_read = false'))
    op.create_table('reports',
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('format', sa.Enum('pdf', 'json', 'csv', name='report_format'), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_reports_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_reports_generated_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_reports_storage_key'))
    )
    op.create_index(op.f('ix_reports_application_id'), 'reports', ['application_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('band', sa.Enum('low', 'medium', 'high', name='risk_band'), nullable=False),
    sa.Column('recommendation', sa.Enum('auto_approve_candidate', 'needs_review', 'high_risk_reject_candidate', name='recommendation'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('component_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weights_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_risk_scores_confidence_range')),
    sa.CheckConstraint('score BETWEEN 0 AND 1', name=op.f('ck_risk_scores_score_range')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_risk_scores_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_scores'))
    )
    op.create_index(op.f('ix_risk_scores_application_id'), 'risk_scores', ['application_id'], unique=False)
    op.create_index('ix_risk_scores_band', 'risk_scores', ['band'], unique=False)
    op.create_index('uq_risk_scores_current', 'risk_scores', ['application_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('verification_results',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('ingest', 'frame_extraction', 'face_detection', 'face_embedding', 'face_match', 'audio_extraction', 'transcription', 'consent_detection', 'intent_analysis', 'fraud_check', 'risk_scoring', name='verification_stage'), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'skipped', name='stage_status'), server_default='pending', nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('consent', sa.Enum('explicit_yes', 'ambiguous', 'explicit_no', 'not_detected', name='consent_status'), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_reason', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt >= 1', name=op.f('ck_verification_results_attempt_positive')),
    sa.CheckConstraint('confidence IS NULL OR (confidence BETWEEN 0 AND 1)', name=op.f('ck_verification_results_confidence_range')),
    sa.CheckConstraint('similarity_score IS NULL OR (similarity_score BETWEEN 0 AND 1)', name=op.f('ck_verification_results_similarity_score_range')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_verification_results_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_results')),
    sa.UniqueConstraint('application_id', 'stage', 'attempt', name='stage_attempt')
    )
    op.create_index('ix_verification_results_app_stage', 'verification_results', ['application_id', 'stage'], unique=False)
    op.create_index('ix_verification_results_payload', 'verification_results', ['payload'], unique=False, postgresql_using='gin')
    op.create_table('artifacts',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('co_applicant_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('applicant_photo', 'coapplicant_photo', 'verification_video', 'document', name='artifact_kind'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'uploaded', 'ingested', 'validated', 'rejected', 'purged', name='artifact_status'), server_default='pending', nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_artifacts_size_bytes_non_negative')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_artifacts_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['co_applicant_id'], ['co_applicants.id'], name=op.f('fk_artifacts_co_applicant_id_co_applicants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_artifacts_storage_key'))
    )
    op.create_index(op.f('ix_artifacts_application_id'), 'artifacts', ['application_id'], unique=False)
    op.create_index('ix_artifacts_checksum', 'artifacts', ['checksum_sha256'], unique=False)
    op.create_index('ix_artifacts_kind', 'artifacts', ['application_id', 'kind'], unique=False)
    op.create_index('uq_artifacts_singleton_kind', 'artifacts', ['application_id', 'kind'], unique=True, postgresql_where=sa.text("kind IN ('applicant_photo','coapplicant_photo','verification_video') AND status <> 'rejected' AND purged_at IS NULL"))
    op.create_table('officer_decisions',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('officer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('approve', 'reject', 'request_more_info', name='decision_type'), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('risk_score_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_officer_decisions_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], name=op.f('fk_officer_decisions_officer_id_officers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], name=op.f('fk_officer_decisions_risk_score_id_risk_scores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_officer_decisions'))
    )
    op.create_index('ix_officer_decisions_application', 'officer_decisions', ['application_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_officer_decisions_officer_id'), 'officer_decisions', ['officer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_officer_decisions_officer_id'), table_name='officer_decisions')
    op.drop_index('ix_officer_decisions_application', table_name='officer_decisions')
    op.drop_table('officer_decisions')
    op.drop_index('uq_artifacts_singleton_kind', table_name='artifacts', postgresql_where=sa.text("kind IN ('applicant_photo','coapplicant_photo','verification_video') AND status <> 'rejected' AND purged_at IS NULL"))
    op.drop_index('ix_artifacts_kind', table_name='artifacts')
    op.drop_index('ix_artifacts_checksum', table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_application_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_verification_results_payload', table_name='verification_results', postgresql_using='gin')
    op.drop_index('ix_verification_results_app_stage', table_name='verification_results')
    op.drop_table('verification_results')
    op.drop_index('uq_risk_scores_current', table_name='risk_scores', postgresql_where=sa.text('is_current'))
    op.drop_index('ix_risk_scores_band', table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_application_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_reports_application_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_notifications_recipient_unread', table_name='notifications', postgresql_where=sa.text('is_read = false'))
    op.drop_table('notifications')
    op.drop_index(op.f('ix_co_applicants_application_id'), table_name='co_applicants')
    op.drop_table('co_applicants')
    op.drop_index('ix_audit_logs_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_application', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index('ix_applications_review_queue', table_name='applications', postgresql_where=sa.text("status = 'pending_review'"))
    op.drop_index(op.f('ix_applications_assigned_officer_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_applicant_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index('uq_risk_engine_config_active', table_name='risk_engine_config', postgresql_where=sa.text('is_active'))
    op.drop_table('risk_engine_config')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('officers')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # SQLAlchemy creates ENUM types implicitly but does not drop them; drop
    # explicitly so a downgrade leaves a clean schema.
    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
